name: Build and deploy Apps to ACR

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/apps.yml"
      - "src/Apps/**"
  workflow_dispatch:
    

env:
  SUBSCRIPTIONID: c38893c4-15b8-4925-bad8-f5486addcc7d
  RESOURCEGROUP: Demo
  ACR: ramardeni

jobs:
  build:
    name: Build Apps
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: ACR Build Producer
      run: |
        cd src/Apps/ServiceBus
        az acr build --image service-bus/queue-producer:${GITHUB_SHA::8} \
          --registry $ACR \
          --file ServiceBusQueueProducer/Dockerfile .

    - name: ACR Build Reader
      run: |
        cd src/Apps/ServiceBus
        az acr build --image service-bus/queue-reader:${GITHUB_SHA::8} \
          --registry $ACR \
          --file ServiceBusQueueReader/Dockerfile .

