name: Build and deploy Apps to ACR

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/apps.yml"
      - "src/Apps/**"
  workflow_dispatch:
    

env:
  SUBSCRIPTIONID: c38893c4-15b8-4925-bad8-f5486addcc7d
  RESOURCEGROUP: Demo
  ACR: ramardeni

jobs:
  build:
    name: Build Apps
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_USERNAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: ACR Build Producer
      id: acrProducer
      uses: azure/acr-build@v1
      with:
        registry: ${{ env.ACR }}
        repository: ServiceBus
        image: ServiceBusQueueProducer
        folder: src/Apps/ServiceBus/ServiceBusQueueProducer

    - name: ACR Build Reader
      id: acrReader
      uses: azure/acr-build@v1
      with:
        registry: ${{ env.ACR }}
        repository: ServiceBus
        image: ServiceBusQueueReader
        folder: src/Apps/ServiceBus/ServiceBusQueueReader

